### ISSUE TITLE
官方已更新定制样式的语法

### ISSUE THREAD

**Issue by SetsuikiHyoryu** [thep0y/rime-98#2]
## 新语法

```yaml
path:
  style/<style-name>: <value>
```

## 官方案例

<https://gist.github.com/lotem/2290714>

## 我的环境

|名称|版本|
|-|-|
|macOS Monterey|12.5|
|鼠须管|0.15.2|

\* 我的环境中旧语法已经无法导入主题

**Comment by thep0y** [comment]
我很久不用mac了，没办法进行测试，只能请你试一下将 [squirrel.custom.yaml](https://github.com/thep0y/rime-98/blob/master/%E7%9A%AE%E8%82%A4/squirrel.custom.yaml) 改成下面这样是否可行：
```yaml
patch:
  preset_color_schemes:
    mojave_dark:
      author: "xiehuc <xiehuc@gmail.com>"
      back_color: 0x252320
      border_color: 0x020202
      border_color_width: 0
      border_height: 6
      border_width: 6
      candidate_format: "%c %@"
      candidate_text_color: 0xdedddd
      comment_text_color: 0xdedddd
      corner_radius: 5
      font_face: PingFangSC
      font_point: 16
      hilited_back_color: 0x252320
      hilited_candidate_back_color: 0xcb5d00
      hilited_candidate_label_color: 0xffffff
      hilited_candidate_text_color: 0xffffff
      hilited_corner_radius: 3
      hilited_text_color: 0xdedddd
      horizontal: true
      inline_preedit: true
      label_color: 0x888785
      label_font_point: 14
      name: "沙漠夜／Mojave Dark"
      text_color: 0xdedddd
  style:
      color_scheme: mojave_dark
```

**Comment by SetsuikiHyoryu** [comment]
@thep0y 

我用的就是你目录里的 `squirrel.custom.yaml` 文件，结果是不能生效。

我修改后的样子：

```yaml
preset_color_schemes:
  mojave_dark:
    author: "xiehuc <xiehuc@gmail.com>"
    back_color: 0x252320
    border_color: 0x020202
    border_color_width: 0
    border_height: 6
    border_width: 6
    candidate_format: "%c %@"
    candidate_text_color: 0xdedddd
    comment_text_color: 0xdedddd
    corner_radius: 5
    font_face: PingFangSC
    font_point: 16
    hilited_back_color: 0x252320
    hilited_candidate_back_color: 0xcb5d00
    hilited_candidate_label_color: 0xffffff
    hilited_candidate_text_color: 0xffffff
    hilited_corner_radius: 3
    hilited_text_color: 0xdedddd
    horizontal: true
    inline_preedit: true
    label_color: 0x888785
    label_font_point: 14
    name: "沙漠夜／Mojave Dark"
    text_color: 0xdedddd

patch:
  style/color_scheme: mojave_dark
  
# 过时写法，不能生效
# style:
#  color_scheme: mojave_dark
```
